type MarketParams = {
    startDay: number,
    endDay: number,
    startHour: number,
    endHour: number,
}

const marketParams = {
    startDay: 0, // 1 = Monday, 0 = Sunday
    endDay: 6, // 5 = Friday, 6 = Saturday
    startHour: 2, // 9 = Requests after 9:00
    endHour: 23.8, // 17.5 = Request before 17:30
} as MarketParams

type RequestParams = {
    loopTime: number,
    timeout: number,
    margin: number,
    selection: string,
    concurrentPageDownloads: number
}

const requestParams = {
    loopTime: 60 * 1000, // milliseconds
    timeout: 55 * 1000, // milliseconds
    margin: 3 * 1000, // milliseconds
    selection: '.c-faceplate__fluctuation .c-instrument--variation', // targeted className's parent className and targeted className
    concurrentPageDownloads: 48,
} as RequestParams

const csvFolderPath: string = './csv';

const urls: string[] = [
    "https://www.boursorama.com/cours/1rPAC",
    "https://www.boursorama.com/cours/1rPADP",
    "https://www.boursorama.com/cours/1rPAIR",
    "https://www.boursorama.com/cours/1rPAF",
    "https://www.boursorama.com/cours/1rPAI",
    "https://www.boursorama.com/cours/1rPAKA",
    "https://www.boursorama.com/cours/1rPABIO",
    "https://www.boursorama.com/cours/1rPALD",
    "https://www.boursorama.com/cours/1rPALO",
    "https://www.boursorama.com/cours/1rPATE",
    "https://www.boursorama.com/cours/1rPAMUN",
    "https://www.boursorama.com/cours/1rAAPAM",
    "https://www.boursorama.com/cours/1rAMT",
    "https://www.boursorama.com/cours/1rPAKE",
    "https://www.boursorama.com/cours/1rPATO",
    "https://www.boursorama.com/cours/1rPCS",
    "https://www.boursorama.com/cours/1rPBLC",
    "https://www.boursorama.com/cours/1rPBEN",
    "https://www.boursorama.com/cours/1rPBB",
    "https://www.boursorama.com/cours/1rPBIM",
    "https://www.boursorama.com/cours/1rPBNP",
    "https://www.boursorama.com/cours/1rPBOL",
    "https://www.boursorama.com/cours/1rPEN",
    "https://www.boursorama.com/cours/1rPBVI",
    "https://www.boursorama.com/cours/1rPCAP",
    "https://www.boursorama.com/cours/1rPCARM",
    "https://www.boursorama.com/cours/1rPCA",
    "https://www.boursorama.com/cours/1rPCO",
    "https://www.boursorama.com/cours/1rEPALCLS",
    "https://www.boursorama.com/cours/1rPCGG",
    "https://www.boursorama.com/cours/1rPCNP",
    "https://www.boursorama.com/cours/1rPCOFA",
    "https://www.boursorama.com/cours/1rPCOV",
    "https://www.boursorama.com/cours/1rPACA",
    "https://www.boursorama.com/cours/1rPBN",
    "https://www.boursorama.com/cours/1rPAM",
    "https://www.boursorama.com/cours/1rPDSY",
    "https://www.boursorama.com/cours/1rPDBV",
    "https://www.boursorama.com/cours/1rPDBG",
    "https://www.boursorama.com/cours/1rPDVT",
    "https://www.boursorama.com/cours/1rPEDEN",
    "https://www.boursorama.com/cours/1rPEDF",
    "https://www.boursorama.com/cours/1rPFGR",
    "https://www.boursorama.com/cours/1rPEKI",
    "https://www.boursorama.com/cours/1rPELIOR",
    "https://www.boursorama.com/cours/1rPELIS",
    "https://www.boursorama.com/cours/1rPENGI",
    "https://www.boursorama.com/cours/1rPERA",
    "https://www.boursorama.com/cours/1rPEL",
    "https://www.boursorama.com/cours/1rPRF",
    "https://www.boursorama.com/cours/1rPERF",
    "https://www.boursorama.com/cours/1rPENX",
    "https://www.boursorama.com/cours/1rPEUCAR",
    "https://www.boursorama.com/cours/1rPETL",
    "https://www.boursorama.com/cours/1rPEO",
    "https://www.boursorama.com/cours/1rPFNAC",
    "https://www.boursorama.com/cours/1rPALFPC",
    "https://www.boursorama.com/cours/1rPGFC",
    "https://www.boursorama.com/cours/1rPGNFT",
    "https://www.boursorama.com/cours/1rPGET",
    "https://www.boursorama.com/cours/1rPGTT",
    "https://www.boursorama.com/cours/1rPRMS",
    "https://www.boursorama.com/cours/1rPHEXA",
    "https://www.boursorama.com/cours/1rPICAD",
    "https://www.boursorama.com/cours/1rPILD",
    "https://www.boursorama.com/cours/1rPNK",
    "https://www.boursorama.com/cours/1rPIPH",
    "https://www.boursorama.com/cours/1rPITP",
    "https://www.boursorama.com/cours/1rPIPN",
    "https://www.boursorama.com/cours/1rPJCQ",
    "https://www.boursorama.com/cours/1rPDEC",
    "https://www.boursorama.com/cours/1rPKOF",
    "https://www.boursorama.com/cours/1rPKER",
    "https://www.boursorama.com/cours/1rPLI",
    "https://www.boursorama.com/cours/1rPKORI",
    "https://www.boursorama.com/cours/1rPOR",
    "https://www.boursorama.com/cours/1rPMMB",
    "https://www.boursorama.com/cours/1rPLR",
    "https://www.boursorama.com/cours/1rPFII",
    "https://www.boursorama.com/cours/1rPMC",
    "https://www.boursorama.com/cours/1rPMMT",
    "https://www.boursorama.com/cours/1rPMDM",
    "https://www.boursorama.com/cours/1rPMTU",
    "https://www.boursorama.com/cours/1rPMERY",
    "https://www.boursorama.com/cours/1rPMRN",
    "https://www.boursorama.com/cours/1rPML",
    "https://www.boursorama.com/cours/1rPKN",
    "https://www.boursorama.com/cours/1rPNEOEN",
    "https://www.boursorama.com/cours/1rPNEX",
    "https://www.boursorama.com/cours/1rPNXI",
    "https://www.boursorama.com/cours/1rPNOKIA",
    "https://www.boursorama.com/cours/1rPORA",
    "https://www.boursorama.com/cours/1rPORP",
    "https://www.boursorama.com/cours/1rPRI",
    "https://www.boursorama.com/cours/1rPPOM",
    "https://www.boursorama.com/cours/1rPPOXEL",
    "https://www.boursorama.com/cours/1rPPUB",
    "https://www.boursorama.com/cours/1rPQDT",
    "https://www.boursorama.com/cours/1rPRCO",
    "https://www.boursorama.com/cours/1rPRNO",
    "https://www.boursorama.com/cours/1rPRXL",
    "https://www.boursorama.com/cours/1rPRUI",
    "https://www.boursorama.com/cours/1rPSAF",
    "https://www.boursorama.com/cours/1rPSGO",
    "https://www.boursorama.com/cours/1rPSAN",
    "https://www.boursorama.com/cours/1rPDIM",
    "https://www.boursorama.com/cours/1rPSU",
    "https://www.boursorama.com/cours/1rPSCR",
    "https://www.boursorama.com/cours/1rPSK",
    "https://www.boursorama.com/cours/1rPSESG",
    "https://www.boursorama.com/cours/1rPSII",
    "https://www.boursorama.com/cours/1rPGLE",
    "https://www.boursorama.com/cours/1rPSW",
    "https://www.boursorama.com/cours/1rPSOI",
    "https://www.boursorama.com/cours/1rPS30",
    "https://www.boursorama.com/cours/FF11-SOLB",
    "https://www.boursorama.com/cours/1rPSOP",
    "https://www.boursorama.com/cours/1rPSPIE",
    "https://www.boursorama.com/cours/1gSTLA",
    "https://www.boursorama.com/cours/1rPSTM",
    "https://www.boursorama.com/cours/1rPSEV",
    "https://www.boursorama.com/cours/1rPTKTT",
    "https://www.boursorama.com/cours/1rPFTI",
    "https://www.boursorama.com/cours/1rPTEP",
    "https://www.boursorama.com/cours/1rPTFI",
    "https://www.boursorama.com/cours/1rPHO",
    "https://www.boursorama.com/cours/1rPTTE",
    "https://www.boursorama.com/cours/1rPTRI",
    "https://www.boursorama.com/cours/1rPUBI",
    "https://www.boursorama.com/cours/1rAURW",
    "https://www.boursorama.com/cours/1rPFR",
    "https://www.boursorama.com/cours/1rPVK",
    "https://www.boursorama.com/cours/1rPVIE",
    "https://www.boursorama.com/cours/1rPVRLA",
    "https://www.boursorama.com/cours/1rPVCT",
    "https://www.boursorama.com/cours/1rPDG",
    "https://www.boursorama.com/cours/1rPVIRP",
    "https://www.boursorama.com/cours/1rPVIV",
    "https://www.boursorama.com/cours/1rPMF",
    "https://www.boursorama.com/cours/1rPWLN",
    "https://www.boursorama.com/cours/1rP2CRSI"
]

export {
    MarketParams,
    marketParams,
    RequestParams,
    requestParams,
    csvFolderPath,
    urls
}